### PR TITLE
JEI support

### PR DESCRIPTION
**Pull request by ExpensiveKoala**

### CODE REVIEW

**Comment by ExpensiveKoala** [comment]
I have some issues with your latest commit. Also, don't use ISidedInventory. The reason I used IItemHandler is because that is the more "automation friendly" version that forge adds.

Plus, looking through the actual changes, I'm not sure what you changed to fix the ore dictionary issue.

**Comment by KewaiiGamer** [comment]
I will merge your pull request to add JEI support. :D the fix for the Oredict was on the ExtremeShapedOreRecipe class

**Comment by KewaiiGamer** [comment]
It looks like your commit had conflits. since I couldn't resolve them I decided to manually change my files and commit then.

**Comment by KewaiiGamer** [comment]
It looks like it is still buggy. The gui is buggy and doesn't show up properly. Do you think you can fix that?
Clicking "Show all Recipes crashes minecraft!
Using oreDict as input doesn't show up on JEI at all :(

EDIT: Also I would like to invite you to a Discord server. Since I don't want to share my personal discord information on public and this server is public I think I can send you invite here :)
https://discord.gg/dHDG6mP

**Comment by ExpensiveKoala** [comment]
Your latest commits don't touch the ExtremeShapedOreRecipe class. Are your commits not up to date?

Also, I need crash reports and more than "It's buggy"

**Pull request merged**
